### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by anuras** [ap975/Elixir_Chat_App#1]
Hello Artem, I'd like to chat about an Elixir app.

**Comment by ap975** [comment]
Hi, who is there?

**Comment by anuras** [comment]
Hi I saw your profile on Upwork, I posted a job there. Do you have an email I can contact you with?

**Comment by anuras** [comment]
For lead elixir/phoenix developer

**Comment by ap975** [comment]
Can you share job post url?
my mail: ap9755285@gmail.com

**Comment by anuras** [comment]
Ok sending you email with more details
